### ISSUE TITLE
newbi question: supplying data via GitHub

### ISSUE THREAD

**Issue by aubreymoore** [globalbioticinteractions/globalbioticinteractions.github.io#107]
I'm tying to get my feet wet with GloBI. I used the template to create a GitHub repo containing a single interaction record at https://github.com/aubreymoore/Guam-insect-associates-of-Glochidion. How will I know if and when the data were ingested by GloBI?

**Comment by jhpoelen** [comment]
hi @aubreymoore - thanks for asking!

You might have noticed that your review passed, so I'd expected that within a week or so, your data will appear on the GloBI public index. When this happens, your GloBI badge in the README will turn green.

How would you like others to use your species interaction data?

**Comment by aubreymoore** [comment]
I am confused about the code behind the **GloBI review by Elton** button:
```
[![GloBI review by Elton](https://github.com/globalbioticinteractions/template-dataset/actions/workflows/review.yml/badge.svg)](https://github.com/globalbioticinteractions/template-dataset/actions)
```
Do I need to change 
```
https://github.com/globalbioticinteractions/template-dataset/actions
```
to
```
https://github.com/aubreymoore/Guam-insect-associates-of-Glochidian/actions
```
?

A bit of background: I am trying to expose biotic interactions in data harvested from about 40 chapters in Insects of Guam I and II. Datamining was done using PLAZI's Golden Gate tool. All occurrence records are in GBIF, but we also tagged a lot of biotic interactions and, as you know, GBIF does not have a good way to make these accessable. Thanks so much for your help.

**Comment by jhpoelen** [comment]
Yes, you'd need to update the README after creating the repository from the template.  I haven't quite figured out how to make it dynamic. If you have any ideas, please do let me know, 'cause I realize that having to make these edits might reduce the enjoyment of getting your valuable data indexed . . . ; )

Thanks for providing the context, Plazi's tools are pretty amazing as are the people that help maintain them. Please let me know how I can help improve the indexing process from Golden Gate to GloBI (or others). Ideally, this entire workflow can be automated, so you can focus on the completeness/quality of the data rather than having to spend time on configuration.

**Comment by jhpoelen** [comment]
@aubreymoore please comment if you have some additional observations / comments you'd like to share. Am closing issue for now.
