### ISSUE TITLE
stable URLs

### ISSUE THREAD

**Issue by kueda** [globalbioticinteractions/globalbioticinteractions.github.io#16]
When I search for an interaction I expect a URL for the results that I can share, maybe something like `http://www.globalbioticinteractions.org/#taxon=Patiria+miniata&interaction=preys_on`

**Comment by jhpoelen** [comment]
@kueda thanks for suggesting this . . . is it correct to assume that both http://globalbioticinteractions.org and http://globalbioticinteractions.org/browse should have this kind of features? 

In order to be consistent with the GloBI api, I imagine something like:

http://www.globalbioticinteractions.org/?sourceTaxon=Patiria%20miniata&interactionType=preysOn 

Today, I just learned that @danielabar has built a prototype with a similar link feature:
http://danielabar.github.io/globi-proto/#/main?name=Patiria%20miniata&interaction=preysOn 

Is this similar to what you were looking for as far as linking goes?

**Comment by kueda** [comment]
Basically. States in web applications should have stable URLs, particularly if they're interesting enough to share with others. I was specifically thinking about http://www.globalbioticinteractions.org b/c I wanted to show someone an interaction there and realized I couldn't link to it.

**Comment by jhpoelen** [comment]
I made an attempt to implement this (see attached). Please re-open / submit pull request if you have another way of doing this. Hope you can more easily share interactions now!
![screen shot 2015-02-25 at 8 45 58 pm](https://cloud.githubusercontent.com/assets/1084872/6386564/88108230-bd2f-11e4-8f40-00c7b92e2518.png)

**Comment by kueda** [comment]
Cool, seems to be working: http://www.globalbioticinteractions.org/#sourceTaxon=Larus%20occidentalis&interactionType=preysOn. Thanks!
