### ISSUE TITLE
Problem about filtering specific species in GitHub browse

### ISSUE THREAD

**Issue by DupontCai** [globalbioticinteractions/globalbioticinteractions.github.io#7]
Hi, Dear editer:

Thanks so much for sharing the powerful globi browse,This is Dupont, I am having a workshop instructed by @jhpoelen at Texas A&M University, Corpus Christi , however I found myself difficult to filter the interaction linked by a single species I am interested in, (King mackerel，Scomberomorus cavalla) at  http://www.globalbioticinteractions.org/browse/  in the Gulf of Mexico;

So,  I am wondering if you can improve a little bit about the filtering function, Thanks.

Appreciate for your help,
Dupont

**Comment by jhpoelen** [comment]
@coding46 thanks for implementing a way to list interactions for specific taxa in the table view in the interaction browser (see attached screenshot)! I am assuming that you are still working on connecting the table view with the other visualization, so that the data in the table view is "synced" with the other interaction visualizations. Is this correct? I think it would be great to have these views sync up!

![screen shot 2015-02-13 at 12 07 30 pm](https://cloud.githubusercontent.com/assets/1084872/6194426/1deff1b6-b379-11e4-80b2-db3dc7c73e5a.png)

**Comment by jhpoelen** [comment]
@DupontCai update on this issue - @coding46 implemented an improvement on filtering the interactions by source / target taxa and interaction type. The updating of the visualization in the lower half is described in issue #15 .

**Comment by coding46** [comment]
@jhpoelen Is this still a thing after 548ab1eacd457c9fcea280ffaf70f4d0c9a6650b

**Comment by jhpoelen** [comment]
Described feature is now implemented as described in this issue and in  #15 . 

@DupontCai thanks for waiting and let me know if the feature is working as expected. Please re-open this issue if it is not.
